apiVersion: v1
kind: Service
metadata:
  name: niwanthi-calculator-service
spec:
  selector:
    app: niwanthi-calculator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort
